/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifce.so.projeto.display;

import javax.swing.JOptionPane;

/**
 *
 * @author Nonato Dias
 */
public class DisplayInicio extends javax.swing.JDialog {

    /**
     * Creates new form DisplayInicio
     */
    private int numeroDeCaixas;

    public int getNumeroDeCaixas() {
        return numeroDeCaixas;
    }

    public void setNumeroDeCaixas(int numeroDeCaixas) {
        this.numeroDeCaixas = numeroDeCaixas;
    }
    
    public DisplayInicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Imagem = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Caixas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco do IFCE");
        setResizable(false);

        jLabel_Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ifce/so/projeto/display/imagens/Inicio.png"))); // NOI18N

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.setName(""); // NOI18N
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Digite o número de caixas do Banco");

        jTextField_Caixas.setName("TexteNCaixa"); // NOI18N
        jTextField_Caixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CaixasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Caixas, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(625, 625, 625)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Caixas)
                    .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        int num;
        try{
            num = Integer.parseInt(jTextField_Caixas.getText());
            if(num > 0 && num <= 5){
                setNumeroDeCaixas(num);
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Digite um numero inteiro entre 1 e 5 ","VALOR INCORRETO", JOptionPane.ERROR_MESSAGE);
                jTextField_Caixas.setText(null);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Digite um numero inteiro ","VALOR INCORRETO", JOptionPane.ERROR_MESSAGE);
            jTextField_Caixas.setText(null);
        }
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jTextField_CaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CaixasActionPerformed
        int num;
        try{
            num = Integer.parseInt(jTextField_Caixas.getText());
            if(num > 0 && num <= 5){
                setNumeroDeCaixas(num);
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Digite um numero inteiro entre 1 e 5 ","VALOR INCORRETO", JOptionPane.ERROR_MESSAGE);
                jTextField_Caixas.setText(null);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Digite um numero inteiro ","VALOR INCORRETO", JOptionPane.ERROR_MESSAGE);
            jTextField_Caixas.setText(null);
        }
    }//GEN-LAST:event_jTextField_CaixasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DisplayInicio dialog = new DisplayInicio(new javax.swing.JFrame(), true);
                
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                        //System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Imagem;
    private javax.swing.JTextField jTextField_Caixas;
    // End of variables declaration//GEN-END:variables
}
